#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-only
# MuseScore-Studio-CLA-applies
#
# Seeds the muse dependency cache before configuring the macOS build.
#
# The muse submodule fetches some dependencies from musescore/muse_deps using
# the layout <name>/<version>/<name>.cmake. That layout was removed upstream
# when muse_deps was reorganised into recipes/, so those URLs now return 404.
# muse does not check the download status, so CMake include()s an empty file and
# configure dies with: Unknown CMake command "<name>_Populate".
#
# muse only downloads when the files are not already present in the build tree,
# so we place them here instead of editing the submodule.
#
# The macOS configure needs three of these: harfbuzz (always), vst3sdk
# (MUSESCORE_BUILD_VST_MODULE=ON) and fdk-aac (MUSE_MODULE_AUDIO_EXPORT=ON).
# kddockwidgets requires KDDW v2 (off) and asiosdk is Windows-only.
#
# Sources come from the upstream projects, pinned by SHA-256 or by tag, rather
# than from a mirror of the removed muse_deps payload.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

BUILD_DIR="${1:-}"
if [[ -z "$BUILD_DIR" ]]; then
    echo "usage: $(basename "$0") <build-dir>" >&2
    exit 1
fi

mkdir -p "$BUILD_DIR"
BUILD_DIR="$(cd "$BUILD_DIR" && pwd)"
DEPS_DIR="$BUILD_DIR/_deps"

# macOS ships shasum rather than GNU coreutils sha256sum.
verify_sha256() {
    local file="$1" expected="$2" actual
    if command -v sha256sum >/dev/null 2>&1; then
        actual="$(sha256sum "$file" | cut -d' ' -f1)"
    else
        actual="$(shasum -a 256 "$file" | cut -d' ' -f1)"
    fi
    if [[ "$actual" != "$expected" ]]; then
        echo "error: $file failed checksum verification" >&2
        echo "  expected: $expected" >&2
        echo "  actual:   $actual" >&2
        rm -f "$file"
        exit 1
    fi
}

###############################################################################
# harfbuzz
#
# Must match muse/framework/draw/cmake/SetupHarfBuzz.cmake, which includes
# <dep>/harfbuzz.cmake, add_subdirectory()s <dep>/harfbuzz and expects the
# headers in <dep>/harfbuzz/harfbuzz/src.
###############################################################################
HARFBUZZ_VERSION="12.3.0"
HARFBUZZ_SHA256="8660ebd3c27d9407fc8433b5d172bafba5f0317cb0bb4339f28e5370c93d42b7"
HARFBUZZ_URL="https://github.com/harfbuzz/harfbuzz/releases/download/${HARFBUZZ_VERSION}/harfbuzz-${HARFBUZZ_VERSION}.tar.xz"

HB_DEP_DIR="$DEPS_DIR/harfbuzz"
HB_MODULE_DIR="$HB_DEP_DIR/harfbuzz"
HB_SOURCE_DIR="$HB_MODULE_DIR/harfbuzz"
HB_ARCHIVE="$HB_DEP_DIR/harfbuzz-${HARFBUZZ_VERSION}.tar.xz"

seed_harfbuzz() {
    if [[ ! -f "$HB_SOURCE_DIR/src/harfbuzz.cc" ]]; then
        mkdir -p "$HB_DEP_DIR"

        if [[ ! -f "$HB_ARCHIVE" ]]; then
            echo "Downloading harfbuzz ${HARFBUZZ_VERSION}..."
            curl -fsSL --retry 3 -o "$HB_ARCHIVE.tmp" "$HARFBUZZ_URL"
            mv "$HB_ARCHIVE.tmp" "$HB_ARCHIVE"
        fi

        verify_sha256 "$HB_ARCHIVE" "$HARFBUZZ_SHA256"

        local tmp_dir
        tmp_dir="$(mktemp -d "$HB_DEP_DIR/extract.XXXXXX")"
        trap 'rm -rf "$tmp_dir"' RETURN

        tar -xJf "$HB_ARCHIVE" -C "$tmp_dir"

        rm -rf "$HB_SOURCE_DIR"
        mkdir -p "$HB_MODULE_DIR"
        mv "$tmp_dir/harfbuzz-${HARFBUZZ_VERSION}" "$HB_SOURCE_DIR"

        echo "Seeded harfbuzz ${HARFBUZZ_VERSION} into $HB_SOURCE_DIR"
    else
        echo "harfbuzz sources already seeded"
    fi

    cp "$SCRIPT_DIR/deps/harfbuzz/CMakeLists.txt" "$HB_MODULE_DIR/CMakeLists.txt"

    cat > "$HB_DEP_DIR/harfbuzz.cmake" <<'EOF'
# Generated by buildscripts/ci/macos/seed_muse_deps.sh - do not edit.

function(harfbuzz_Populate remote_url local_path os arch build_type)
    if (NOT EXISTS ${local_path}/harfbuzz/harfbuzz/src/harfbuzz.cc)
        message(FATAL_ERROR "[harfbuzz] seeded sources are missing in ${local_path}")
    endif()
endfunction()
EOF
}

###############################################################################
# vst3sdk
#
# muse/framework/vst/sdk/CMakeLists.txt includes <dep>/vst3sdk.cmake and then
# uses <dep> itself as VST3_SDK_PATH, so the SDK tree has to sit at the root of
# the dependency directory. Only base, pluginterfaces and public.sdk are
# referenced, so the other submodules are skipped.
###############################################################################
VST3_TAG="v3.7.12_build_20"
VST3_URL="https://github.com/steinbergmedia/vst3sdk.git"
VST3_DEP_DIR="$DEPS_DIR/vst3sdk"

seed_vst3sdk() {
    if [[ ! -f "$VST3_DEP_DIR/base/source/baseiids.cpp" ]]; then
        echo "Cloning VST3 SDK ${VST3_TAG}..."
        rm -rf "$VST3_DEP_DIR"
        mkdir -p "$(dirname "$VST3_DEP_DIR")"
        git -c advice.detachedHead=false clone --quiet --depth 1 --branch "$VST3_TAG" --shallow-submodules \
            --recurse-submodules=base \
            --recurse-submodules=pluginterfaces \
            --recurse-submodules=public.sdk \
            "$VST3_URL" "$VST3_DEP_DIR"
        echo "Seeded VST3 SDK ${VST3_TAG} into $VST3_DEP_DIR"
    else
        echo "VST3 SDK already seeded"
    fi

    cat > "$VST3_DEP_DIR/vst3sdk.cmake" <<'EOF'
# Generated by buildscripts/ci/macos/seed_muse_deps.sh - do not edit.

function(vst3sdk_Populate remote_url local_path os arch build_type)
    if (NOT EXISTS ${local_path}/base/source/baseiids.cpp)
        message(FATAL_ERROR "[vst3sdk] seeded sources are missing in ${local_path}")
    endif()
endfunction()
EOF
}

###############################################################################
# fdk-aac
#
# muse/buildscripts/cmake/MuseDeps.cmake includes <dep>/fdk-aac.cmake; the
# descriptor fetches and builds the codec itself.
###############################################################################
seed_fdk_aac() {
    mkdir -p "$DEPS_DIR/fdk-aac"
    cp "$SCRIPT_DIR/deps/fdk-aac.cmake" "$DEPS_DIR/fdk-aac/fdk-aac.cmake"
    echo "Seeded fdk-aac descriptor into $DEPS_DIR/fdk-aac"
}

seed_harfbuzz
seed_vst3sdk
seed_fdk_aac

echo "muse dependency cache seeded in $DEPS_DIR"
