#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-only
# MuseScore-Studio-CLA-applies

set -euo pipefail
trap 'echo Android build failed' ERR

ARTIFACTS_DIR=build.artifacts
BUILD_DIR=build.android.release
BUILD_NUMBER=""
BUILD_MODE=""
ABI="arm64-v8a"

while [[ "$#" -gt 0 ]]; do
    case "$1" in
        -n|--number) BUILD_NUMBER="$2"; shift ;;
        --build_mode) BUILD_MODE="$2"; shift ;;
        --abi) ABI="$2"; shift ;;
        *) echo "Unknown parameter: $1"; exit 1 ;;
    esac
    shift
done

if [[ -z "$BUILD_NUMBER" ]]; then
    echo "error: BUILD_NUMBER is required" >&2
    exit 1
fi

if [[ -z "$BUILD_MODE" ]]; then
    BUILD_MODE="$(cat "$ARTIFACTS_DIR/env/build_mode.env")"
fi

MUSE_APP_BUILD_MODE=dev
case "$BUILD_MODE" in
    devel|nightly) MUSE_APP_BUILD_MODE=dev ;;
    testing) MUSE_APP_BUILD_MODE=testing ;;
    stable) MUSE_APP_BUILD_MODE=release ;;
    *) echo "Unsupported build mode: $BUILD_MODE" >&2; exit 1 ;;
esac

if [[ -z "${QT_ROOT_DIR:-}" ]]; then
    echo "error: QT_ROOT_DIR is not set" >&2
    echo "hint: export QT_ROOT_DIR=/path/to/Qt/<version>/android_arm64_v8a" >&2
    exit 1
fi
if [[ -z "${ANDROID_SDK_ROOT:-}" ]]; then
    echo "error: ANDROID_SDK_ROOT is not set" >&2
    echo "hint: export ANDROID_SDK_ROOT=\$HOME/Android/Sdk" >&2
    exit 1
fi
if [[ -z "${ANDROID_NDK_ROOT:-}" ]]; then
    echo "error: ANDROID_NDK_ROOT is not set" >&2
    echo "hint: export ANDROID_NDK_ROOT=\$ANDROID_SDK_ROOT/ndk/28.0.12916984" >&2
    exit 1
fi

MUSESCORE_REVISION="$(git rev-parse --short=7 HEAD)"

mkdir -p "$BUILD_DIR"

cmake -S . -B "$BUILD_DIR" -GNinja \
    -Wno-deprecated \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_TOOLCHAIN_FILE="$QT_ROOT_DIR/lib/cmake/Qt6/qt.toolchain.cmake" \
    -DQT_HOST_PATH="${QT_HOST_PATH:-$QT_ROOT_DIR}" \
    -DANDROID_SDK_ROOT="$ANDROID_SDK_ROOT" \
    -DANDROID_NDK_ROOT="$ANDROID_NDK_ROOT" \
    -DANDROID_ABI="$ABI" \
    -DMUSESCORE_BUILD_CONFIGURATION=app \
    -DMUSE_APP_BUILD_MODE="$MUSE_APP_BUILD_MODE" \
    -DMUSESCORE_BUILD_NUMBER="$BUILD_NUMBER" \
    -DMUSESCORE_REVISION="$MUSESCORE_REVISION" \
    -DMUE_ANDROID_TABLET_DESKTOP_EXPERIENCE=ON

cmake --build "$BUILD_DIR" --parallel

# Prefer standard Android artifact locations generated by Qt/CMake.
mapfile -t ANDROID_ARTIFACTS < <(find "$BUILD_DIR" -type f \( -name "*.apk" -o -name "*.aab" \) | LC_ALL=C sort)
if [[ "${#ANDROID_ARTIFACTS[@]}" -eq 0 ]]; then
    echo "error: no APK/AAB artifact found under $BUILD_DIR" >&2
    exit 1
fi

mkdir -p "$ARTIFACTS_DIR/android"
for artifact in "${ANDROID_ARTIFACTS[@]}"; do
    cp "$artifact" "$ARTIFACTS_DIR/android/"
done

echo "Collected Android artifacts:"
for artifact in "${ANDROID_ARTIFACTS[@]}"; do
    echo "- $(basename "$artifact")"
done
