#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-only
# MuseScore-Studio-CLA-applies
#
# Seeds the muse dependency cache before configuring the Android build.
#
# The muse submodule fetches some dependencies from musescore/muse_deps using
# the layout <name>/<version>/<name>.cmake. That layout was removed upstream
# when muse_deps was reorganised into recipes/, so those URLs now return 404.
# muse does not check the download status, so CMake include()s an empty file and
# configure dies with: Unknown CMake command "<name>_Populate".
#
# muse only downloads when the files are not already present in the build tree,
# so we place them here instead of editing the submodule (muse changes must stay
# as patches, and this needs no source change at all).
#
# harfbuzz is the only remote dependency the Android configure still needs:
# kddockwidgets requires KDDW v2 (off), asiosdk is Windows-only, and vst3sdk and
# fdk-aac belong to modules disabled for Android in build.sh.
#
# Sources come from the harfbuzz upstream release, pinned by SHA-256, rather
# than from a third-party mirror of the removed muse_deps payload.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

BUILD_DIR="${1:-}"
if [[ -z "$BUILD_DIR" ]]; then
    echo "usage: $(basename "$0") <build-dir>" >&2
    exit 1
fi

mkdir -p "$BUILD_DIR"
BUILD_DIR="$(cd "$BUILD_DIR" && pwd)"

HARFBUZZ_VERSION="12.3.0"
HARFBUZZ_SHA256="8660ebd3c27d9407fc8433b5d172bafba5f0317cb0bb4339f28e5370c93d42b7"
HARFBUZZ_URL="https://github.com/harfbuzz/harfbuzz/releases/download/${HARFBUZZ_VERSION}/harfbuzz-${HARFBUZZ_VERSION}.tar.xz"

# Must match muse/framework/draw/cmake/SetupHarfBuzz.cmake, which includes
# <dep>/harfbuzz.cmake, add_subdirectory()s <dep>/harfbuzz and expects the
# headers in <dep>/harfbuzz/harfbuzz/src.
DEP_DIR="$BUILD_DIR/_deps/harfbuzz"
MODULE_DIR="$DEP_DIR/harfbuzz"
SOURCE_DIR="$MODULE_DIR/harfbuzz"
DESCRIPTOR="$DEP_DIR/harfbuzz.cmake"
ARCHIVE="$DEP_DIR/harfbuzz-${HARFBUZZ_VERSION}.tar.xz"

seed_harfbuzz_sources() {
    if [[ -f "$SOURCE_DIR/src/harfbuzz.cc" ]]; then
        echo "harfbuzz sources already seeded"
        return
    fi

    mkdir -p "$DEP_DIR"

    if [[ ! -f "$ARCHIVE" ]]; then
        echo "Downloading harfbuzz ${HARFBUZZ_VERSION}..."
        curl -fsSL --retry 3 -o "$ARCHIVE.tmp" "$HARFBUZZ_URL"
        mv "$ARCHIVE.tmp" "$ARCHIVE"
    fi

    echo "${HARFBUZZ_SHA256}  ${ARCHIVE}" | sha256sum --check --status || {
        echo "error: harfbuzz archive failed checksum verification" >&2
        rm -f "$ARCHIVE"
        exit 1
    }

    local tmp_dir
    tmp_dir="$(mktemp -d "$DEP_DIR/extract.XXXXXX")"
    trap 'rm -rf "$tmp_dir"' RETURN

    tar -xJf "$ARCHIVE" -C "$tmp_dir"

    rm -rf "$SOURCE_DIR"
    mkdir -p "$MODULE_DIR"
    mv "$tmp_dir/harfbuzz-${HARFBUZZ_VERSION}" "$SOURCE_DIR"

    echo "Seeded harfbuzz ${HARFBUZZ_VERSION} into $SOURCE_DIR"
}

seed_harfbuzz_sources

cp "$SCRIPT_DIR/deps/harfbuzz/CMakeLists.txt" "$MODULE_DIR/CMakeLists.txt"

# Stands in for the descriptor muse would have downloaded; the sources are
# already in place, so this only verifies the layout muse is about to use.
cat > "$DESCRIPTOR" <<'EOF'
# Generated by buildscripts/ci/android/seed_muse_deps.sh - do not edit.

function(harfbuzz_Populate remote_url local_path os arch build_type)
    if (NOT EXISTS ${local_path}/harfbuzz/harfbuzz/src/harfbuzz.cc)
        message(FATAL_ERROR "[harfbuzz] seeded sources are missing in ${local_path}")
    endif()
endfunction()
EOF

echo "muse dependency cache seeded in $DEP_DIR"
